import 'package:flutter/material.dart';

class ListTileDemo extends StatelessWidget {
  const ListTileDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          ListTile(
            leading: const Icon(Icons.menu),
            title: const Text("List Tile Demo"),
            subtitle: const Text("Practice"),
            trailing: const Text("12:50 pm"),
            contentPadding: const EdgeInsets.all(10),
            tileColor: Colors.red,
            dense: false,
            // horizontalTitleGap: 30,
            // isThreeLine: true,
            // minLeadingWidth: 50,
            // minVerticalPadding: 100,
            shape: Border.all(),
            onTap: () {},
            // style: ListTileStyle.drawer,
            // visualDensity: VisualDensity.standard,
            // textColor: Colors.white,
            // hoverColor: Colors.white,
            focusColor: Colors.white,
            // iconColor: Colors.white,
            // selected: true,
            // selectedTileColor: Colors.yellow,
            // selectedColor: Colors.red,
            // splashColor: Colors.blue,
          ),
          ListTile(
            leading: const Icon(Icons.menu),
            title: const Text("List Tile Demo"),
            subtitle: const Text("Practice"),
            trailing: const Text("12:50 pm"),
            contentPadding: const EdgeInsets.all(10),
            tileColor: Colors.red,
            dense: false,
            // horizontalTitleGap: 30,
            // isThreeLine: true,
            // minLeadingWidth: 50,
            // minVerticalPadding: 100,
            shape: Border.all(),
            onTap: () {},
            // style: ListTileStyle.drawer,
            // visualDensity: VisualDensity.standard,
            // textColor: Colors.white,
            // hoverColor: Colors.white,
            focusColor: Colors.white,
            // iconColor: Colors.white,
            // selected: true,
            // selectedTileColor: Colors.yellow,
            // selectedColor: Colors.red,
            // splashColor: Colors.blue,
          ),
          ListTile(
            leading: const Icon(Icons.menu),
            title: const Text("List Tile Demo"),
            subtitle: const Text("Practice"),
            trailing: const Text("12:50 pm"),
            contentPadding: const EdgeInsets.all(10),
            tileColor: Colors.red,
            dense: false,
            // horizontalTitleGap: 30,
            // isThreeLine: true,
            // minLeadingWidth: 50,
            // minVerticalPadding: 100,
            shape: Border.all(),
            onTap: () {},
            // style: ListTileStyle.drawer,
            // visualDensity: VisualDensity.standard,
            // textColor: Colors.white,
            // hoverColor: Colors.white,
            focusColor: Colors.white,
            // iconColor: Colors.white,
            // selected: true,
            // selectedTileColor: Colors.yellow,
            // selectedColor: Colors.red,
            // splashColor: Colors.blue,
          ),
          ListTile(
            leading: const Icon(Icons.menu),
            title: const Text("List Tile Demo"),
            subtitle: const Text("Practice"),
            trailing: const Text("12:50 pm"),
            contentPadding: const EdgeInsets.all(10),
            tileColor: Colors.red,
            dense: false,
            // horizontalTitleGap: 30,
            // isThreeLine: true,
            // minLeadingWidth: 50,
            // minVerticalPadding: 100,
            shape: Border.all(),
            onTap: () {},
            // style: ListTileStyle.drawer,
            // visualDensity: VisualDensity.standard,
            // textColor: Colors.white,
            hoverColor: Colors.white,
            focusColor: Colors.green,
            // iconColor: Colors.white,
            // selected: true,
            // selectedTileColor: Colors.yellow,
            // selectedColor: Colors.red,
            // splashColor: Colors.blue,
          ),
        ],
      ),
    );
  }
}
